### ISSUE TITLE
Button problems in Firefox

### ISSUE THREAD

**Issue by artlantis** [Oaxoa/Conzole#1]
the buttons are not working in Firefox which is not toggle the Conzole panel.

**Comment by Oaxoa** [comment]
Do you mean pressing 'z' for toggling? Thanks for comment, I will work on it right now.

**Comment by Oaxoa** [comment]
Ok should be fixed now. Thanks for debug.

**Comment by artlantis** [comment]
Sorry but still same, any buttons that you mentioned in the sample page does not working ( without focusing any fiedl)

**Comment by Oaxoa** [comment]
Mm totally works for me Firefox v. 24. Maybe a cache problem?

**Comment by artlantis** [comment]
sorry, you were right, it was just a cache problem. Thanks

**Comment by billsaysthis** [comment]
While the keystroke commands do work, when the Firefox setting to search for text on the page automatically on keystrokes is also triggered, I wonder if you need something like e.preventDefault() or e.stopPropagation() to stop that.
